network:
  version: 2
  ethernets:
      ens33:
        dhcp4: false
        addresses:
          - 192.168.xx.xx/xx   #(Input the ip address you want to set with the CIDR)
        routes:
           - to: default
              via: 192.168.xx.xx #(Default Gateway of the network you are using)
         nameservers:
            addresses:
              - 1.1.1.1
              - 1.0.0.1 #(You could equally use 8.8.8.8 and 8.8.4.4 for google but 1.1.1.1 is recommended for cloudflare)



# Then Apply the changes with sudo netplan apply
